### ISSUE TITLE
Tests in different files!

### ISSUE THREAD

**Issue by alistairstead3408** [jsharkey13/isaac-selenium-testing#1]

**Comment by alistairstead3408** [comment]
#issue1

**Comment by jsharkey13** [comment]
This is hard to resolve, because right now the decorator for each test requires the Results object at define time, despite the fact that it's not needed really until the function runtime. This means that they can't be declared in different files and still update the same Results object, without some horrible mess of importing or another results class/object.

Changing how the decorator works might fix this; a class based decorator could contain the internal state required to manage test results; thereby avoiding the issue.
